In [ ]:
import tensorflow as tf
tf.Variable("Hello",tf.string)


<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>

In [ ]:
tf.constant([1,2,3,4,5,6,7])

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
vector = tf.Variable(initial_value=[1,2])

In [ ]:
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
vector = tf.Variable([1,2],dtype=tf.float32)

In [ ]:
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [ ]:
# TF constant vrednosti se ne mogu menjati

In [ ]:
tf.add([2,3],[4,5])
tf.square(5)
tf.reduce_sum([1,2,3])
tf.square(2) + tf.square(3)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [ ]:
import numpy as np
x = np.arange(0,25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [ ]:
x = tf.cast(x,tf.float32)
x

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.,
       121., 144., 169., 196., 225., 256., 289., 324., 361., 400., 441.,
       484., 529., 576.], dtype=float32)>

In [ ]:
class MyLayer(tf.keras.layers.Layer):

    def __init__(self):
        super(MyLayer,self).__init__()
        self.my_var = tf.Variable(100)
        self.my_other_var_list = [tf.Variable(x) for x in range(2)]

m = MyLayer()
[variable.numpy() for variable in m.variables]

[100, 0, 1]

In [ ]:
tensor = tf.constant([1,2,3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
##Gradient Tape

In [ ]:
def simple_loss(real_y,pred_y):
    return tf.abs(real_y - pred_y)

LEARNING_RATE=0.001

In [ ]:
def fit_data(real_x,real_y):
    with tf.GradientTape(persistent=True) as tape:
        #predict
        pred_y = w*real_x+b
        #calculate loss
        reg_loss = simple_loss(real_y,pred_y)

    #calculate gradients
    w_gradient =tape.gradient(reg_loss,w)
    b_gradient = tape.gradient(reg_loss,b)

    #update vars
    w.assign_sub(w_gradient * LEARNING_RATE)
    b.assign_sub(b_gradient * LEARNING RATE)

In [ ]:
for _ in range(500):
    fit_data(x_train,y_train)
print(f'y = {w.numpy()}x + {b.numpy()}')

In [ ]:
def train_step(images,labels):
    with tf.GradientTape() as tape:
        logits = model(images, training=True)
        loss_value = loss_object(labels,logits)

    loss_history.append(loss_value.numpy().mean())
    grads = tape.gradient(loss_value, model.trainable_variables)
    oprimizer.apply_gradients(zip(grads,model.trainable_variables))

In [ ]:
import tensorflow as tf
a = tf.constant([[5,7],[2,1]])
b=tf.add(a,2)
c=b**2
d=tf.reduce_sum(c)
print(d)

tf.Tensor(155, shape=(), dtype=int32)
